# Generated by Django 5.0.2 on 2024-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_role_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopprofile",
            name="avatar",
            field=models.ImageField(default="", upload_to="images/avatars"),
        ),
    ]
