# Generated by Django 5.0.2 on 2024-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_shopprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopprofile",
            name="avatar",
            field=models.ImageField(blank=True, default="", upload_to="images/avatars"),
        ),
    ]
