# Generated by Django 5.0.2 on 2024-06-20 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_shopprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopprofile",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
