# Generated by Django 5.0.2 on 2024-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", null=True, upload_to="images/products"),
        ),
    ]
