# Generated by Django 5.0.2 on 2024-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_orderitem_order_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images/products"
            ),
        ),
    ]
