# Generated by Django 5.0.2 on 2024-07-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shopprofile",
            ),
            preserve_default=False,
        ),
    ]
