name: test_frontend
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
    test_project:
        runs-on: ubuntu-latest # operating system your code will run on
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: pwd
            - run: cd frontend
            - run: pwd
            - run: ls -l
            - run: npm install # install dependences
            - run: npm run test # run tests
