name: test_backend
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
    test_project:
        runs-on: ubuntu-latest # operating system your code will run on
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.12"
            # - run: cd backend
            - run: pip install backend/pipenv
            - run: pipenv install -d # create venv and install all our dependencies for the project
            # - run: pipenv shell # enable venv
            - run: pipenv run python backend/manage.py test # run tests
